### PR TITLE
Add support for reStructuredText

### PR DESCRIPTION
**Pull request by marcw**
Hello! 

Thanks for this plugin. This small change add supports for reStructuredText.

### CODE REVIEW

**Comment by kropp** [comment]
Hi Marc,
thanks for contribution! I have a suggestion: let's make dependencies optional. So that, I don't need to install reST plugin if I don't use it, and you can skip installing Markdown plugin, if you are only writing reStructruredText.

**Comment by marcw** [comment]
@kropp Thanks. This is my first contribution to a jetbrain plugin and I really don't know how to do the changes you ask. I'll try to find some doc on that.

**Comment by kropp** [comment]
`optional="true"` in `depends` tag should do the trick, but need to check it.

**Comment by marcw** [comment]
@kropp Thanks. I added it. It builds and installs. :)

**Comment by kropp** [comment]
Thanks!

**Comment by kropp** [comment]
I've updated plugin, will be available soon

**Pull request merged**
